"""agregar_columna_editorial

Revision ID: 0722c40e8413
Revises: 1007f447150e
Create Date: 2026-04-24 13:03:44.346826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0722c40e8413'
down_revision: Union[str, Sequence[str], None] = '1007f447150e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('editorial', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'editorial')
    # ### end Alembic commands ###
